### ISSUE TITLE
Updating / saving resources

### ISSUE THREAD

**Issue by IdahoEv** [LRDesign/relayer#16]
A couple things I'm unable to find docco on this morning:

1) When looking at a resource, how can I tell if it's a newly created one, or one that has been previously persisted on the backend?

2) How do I save an updated resource?  The only up-to-date example code I have is for saving newly created resources with <resource>.create() as follows:

```
save(user) {
  user.confirmationLink = this.$state.href('root.inner.passwordsUpdate', {}, {absolute: true});
  this.users.create(user).then((user) => {
    this.$state.go('root.admin.users.index');
  },
  (resp) => {
    return this.$lrdToast.error(resp.errors);
  });
}
```

**Comment by IdahoEv** [comment]
I was able to figure this out through a combination of trial and error and inspecting objects in the console.  So, consider this ticket just a request for documentation with a note on where one user was confused.  Current README only gives examples of reading & traversing resources, not creating or updating.

**Comment by nyarly** [comment]
This issue was moved to XingFramework/Relayer#4
